In [1]:
import numpy as np

In [2]:
np.__version__


'1.23.1'

In [4]:
pip show numpy

Name: numpy
Version: 1.23.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\hari om\appdata\local\programs\python\python310\lib\site-packages
Requires: 
Required-by: contourpy, folium, matplotlib, pandas, scikit-learn, scipy, seaborn, yfinance
Note: you may need to restart the kernel to use updated packages.


In [5]:
a = np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [7]:
a.dtype

dtype('int32')

In [8]:
a.shape

(3,)

In [9]:
a.ndim

1

In [10]:
a.size

3

In [11]:
a.itemsize

4

In [12]:
a[0]

1

In [13]:
a[2]

3

In [14]:
a[0] =10

In [15]:
a

array([10,  2,  3])

In [16]:
b = a * np.array([3,0,4])

In [17]:
b

array([30,  0, 12])

In [18]:
l = [1,2,3]

In [19]:
a = np.array([1,2,3])

In [20]:
l

[1, 2, 3]

In [21]:
a

array([1, 2, 3])

In [22]:
l.append(4)

In [24]:
l

[1, 2, 3, 4]

In [25]:
a.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [26]:
l = l + [4]

In [27]:
l

[1, 2, 3, 4, 4]

In [28]:
a= a + np.array([4])

In [29]:
a

array([5, 6, 7])

In [30]:
l = l*2

In [31]:
l

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [32]:
a = a * 2

In [33]:
a

array([10, 12, 14])

In [34]:
np.sqrt(a)

array([3.16227766, 3.46410162, 3.74165739])

In [35]:
np.log(a)

array([2.30258509, 2.48490665, 2.63905733])

In [36]:
a


array([10, 12, 14])

In [37]:
#dot product
l2 = [4,5,6]

In [39]:
l1 = [1,2,3]

In [41]:

l2

[4, 5, 6]

In [42]:
l1

[1, 2, 3]

In [43]:
dot = 0
for i in range(len(l1)):
    dot = l1[i] * l2[i]

In [44]:
dot

18

In [45]:
a1 = np.array(l1)

In [46]:
a2 = np.array(l2)

In [47]:
dot = np.dot(a1,a2)

In [48]:
dot

32

In [50]:
sum1 = a1 * a2

In [51]:
dot = np.sum(sum1)
dot

32

In [52]:
sum1

array([ 4, 10, 18])

In [53]:
dot = (a1* a2).sum()

In [54]:
dot

32

In [55]:
dot = a1 @ a2
dot

32

### Multi Dimensional Array

In [57]:
a= np.array([1,2])

In [58]:
a.shape

(2,)

In [66]:
a = np.array([[1,2,6],[3,4,8]])

In [67]:
a.shape

(2, 3)

In [68]:
a

array([[1, 2, 6],
       [3, 4, 8]])

In [69]:
a[0]


array([1, 2, 6])

In [70]:
a[0,0]

1

In [71]:
a[0][2]

6

In [72]:
a[:,0]

array([1, 3])

In [73]:
a[0,:]

array([1, 2, 6])

In [74]:
a.T

array([[1, 3],
       [2, 4],
       [6, 8]])

In [76]:
b = np.array([[1,2],[3,4]])

In [77]:
b

array([[1, 2],
       [3, 4]])

In [78]:
np.linalg.inv(b)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [79]:
np.linalg.det(b)

-2.0000000000000004

In [82]:
c= np.diag(b)

In [86]:
c

array([1, 4])

In [85]:
np.diag(c)

array([[1, 0],
       [0, 4]])

In [87]:
b


array([[1, 2],
       [3, 4]])

In [88]:
b= a[0,1]

In [89]:
b

2

In [90]:
b = np.array([[1,2,3,4],[3,4,5,6]])

In [91]:
b

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [94]:
b = a[0,2]

In [95]:
b

6

In [97]:
b = a[0,:]

In [98]:
b

array([1, 2, 6])

In [99]:
a

array([[1, 2, 6],
       [3, 4, 8]])

In [100]:
b = a[:,0]

In [101]:
b

array([1, 3])

In [102]:
b= a[-1,-1]

In [103]:
b

8

In [109]:
bool_ind = a >3

In [110]:
bool_ind

array([[False, False,  True],
       [False,  True,  True]])

In [111]:
a[bool_ind]

array([6, 4, 8])

In [112]:
a[a>3]

array([6, 4, 8])

In [113]:
b= np.where(a>3,a,-1)

In [114]:
b

array([[-1, -1,  6],
       [-1,  4,  8]])

In [115]:
a = np.array([19,20,31,43,67,23])

In [116]:
a

array([19, 20, 31, 43, 67, 23])

In [117]:
c = [1,3,5]

In [118]:
a[c]

array([20, 43, 23])

In [119]:
even = np.argwhere(a%2==0).flatten()

In [120]:
even

array([1], dtype=int64)

In [121]:
a[even]

array([20])