In [3]:
import numpy as np

In [2]:
np.__version__

'1.23.1'

In [3]:
pip show numpy

Name: numpy
Version: 1.23.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\hari om\appdata\local\programs\python\python310\lib\site-packages
Requires: 
Required-by: contourpy, folium, matplotlib, pandas, scikit-learn, scipy, seaborn, yfinance
Note: you may need to restart the kernel to use updated packages.


In [4]:
a = np.arange(1,7)

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a.shape

(6,)

In [7]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a.reshape(2,5)

ValueError: cannot reshape array of size 6 into shape (2,5)

In [9]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
b = a[np.newaxis, :]

In [11]:
b

array([[1, 2, 3, 4, 5, 6]])

In [12]:
b.shape


(1, 6)

In [13]:
b = a[:,np.newaxis]

In [14]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
c = np.array([[1,2],[3,4]])

In [18]:
c

array([[1, 2],
       [3, 4]])

In [19]:
d = np.array([[5,6]])

In [21]:
e = np.concatenate((c,d),axis = None)

In [22]:
e

array([1, 2, 3, 4, 5, 6])

In [23]:
e = np.concatenate((c,d),axis = 0)

In [24]:
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
e = np.concatenate((c,d),axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [27]:
e = np.concatenate((c,d.T),axis = 1)

In [28]:
e

array([[1, 2, 5],
       [3, 4, 6]])

In [29]:
f = np.array([1,2,3,4])

In [30]:
g = np.array([5,6,7,8])

In [33]:
h = np.hstack((f,g))

In [34]:
h

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
h = np.vstack((f,g))

In [36]:
h

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])

In [39]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [40]:
a = np.array([0,1,2])

In [41]:
a

array([0, 1, 2])

In [42]:
x + a

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11],
       [ 1,  3,  5]])

In [43]:
x+a.shape

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 4,  5,  6]])

In [45]:
a = np.array([[7,8,9,10,11,12,13],[14,15,16,17,18,19,20]])

In [46]:
a

array([[ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [47]:
a.sum()

189

In [48]:
a.sum(axis = None)

189

In [49]:
a.sum(axis=0)

array([21, 23, 25, 27, 29, 31, 33])

In [50]:
a.sum(axis=1)

array([ 70, 119])

In [51]:
a.mean(axis =None)

13.5

In [52]:
a.mean(axis =1)

array([10., 17.])

In [53]:
a.mean(axis =0)

array([10.5, 11.5, 12.5, 13.5, 14.5, 15.5, 16.5])

In [54]:
a.var(axis =None)

16.25

In [56]:
a.std(axis=None)

4.031128874149275

In [57]:
a.min(axis = None)

7

In [58]:
np.min(a,axis = 1)

array([ 7, 14])

In [59]:
np.min(a,axis = 0)

array([ 7,  8,  9, 10, 11, 12, 13])

In [60]:
a.max()

20

In [66]:
x = np.array([1,2])

In [62]:
x

array([1, 2])

In [67]:
x.dtype

dtype('int32')

In [68]:
x = np.array([1.0,2.0])

In [70]:
x

array([1., 2.])

In [71]:
x.dtype

dtype('float64')

In [77]:
x = np.array([1.0,2.0],dtype=None)

In [78]:
x

array([1., 2.])

In [79]:
x = np.array([1.0,2.0],dtype=np.float16)

In [80]:
x

array([1., 2.], dtype=float16)

In [81]:
x.dtype

dtype('float16')

In [82]:
a = np.array([1,2,3])

In [83]:
b =a

In [84]:
b[0] = 42

In [85]:
b

array([42,  2,  3])

In [86]:
a

array([42,  2,  3])

In [87]:
a

array([42,  2,  3])

In [88]:
b = a.copy()

In [89]:
b

array([42,  2,  3])

In [90]:
b[0] = 30

In [91]:
b

array([30,  2,  3])

In [92]:
a

array([42,  2,  3])

In [93]:
a = np.zeros([2,3])

In [94]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [95]:
a = np.ones([2,3])

In [96]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [97]:
a.dtype

dtype('float64')

In [98]:
a = np.full([2,3],5.0)

In [99]:
a

array([[5., 5., 5.],
       [5., 5., 5.]])

In [101]:
a = np.eye(3)

In [102]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
a = np.arange(20)

In [104]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [105]:
a = np.linspace(1,10,5)

In [106]:
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [4]:
a = np.random.random((3,2))

In [5]:
a

array([[0.60836138, 0.41013416],
       [0.79647381, 0.65086146],
       [0.14314343, 0.93003368]])

In [6]:
a = np.random.randn(3,2)

In [7]:
a

array([[-0.41142435,  0.50751878],
       [ 1.16693703, -0.05602913],
       [-0.84215933, -0.00328368]])

In [8]:
a = np.random.randn(1000)

In [9]:
a.mean()

-0.03337460545863394

In [10]:
a.var()

1.0332172211456094

In [11]:
b = np.random.randint(3,10,size=(3,3))

In [12]:
b

array([[6, 3, 5],
       [3, 6, 4],
       [3, 6, 6]])

In [13]:
b = np.random.randint(0,10,size=(3,3))

In [14]:
b

array([[6, 0, 5],
       [4, 9, 3],
       [6, 9, 4]])

In [15]:
a = np.random.choice(5,size=10)

In [16]:
a

array([3, 1, 0, 0, 0, 0, 4, 0, 4, 0])

In [17]:
a = np.random.choice([-5,-6,-2,9],size=10)

In [18]:
a

array([ 9, -6, -5, -5, -6, -5,  9, -2,  9, -6])